### ISSUE TITLE
Out of order packet reception with vma_cyclic_buffer_read and ring_cyclicb.num greater than 8192

### ISSUE THREAD

**Issue by mplachecki** [Mellanox/libvma#482]
Following the example in section 8.7.2.2 in the VMA User Manual for using multi packet receive queues [here](http://www.mellanox.com/related-docs/prod_acceleration_software/VMA_8_3_7_User_Manual.pdf), when using any value for  vma_ring_type_attr ring.ring_cyclicb.num greater than 8192 the packets are received in out of order chunks, with vma_completion_cb_t completion.packets and completion.payload_length at times showing that there is a packet to read, although the data read from completion.payload_ptr is zeros. The pattern is the same every time, regardless of the packet size or rate. 

- Using all default VMA settings
- Seen with both VMA version 8.3.7 and 8.4.6
- RX with Connect X5
-  vma_ring_type_attr ring.ring_cyclicb.num = 16384 

Pattern of packet reception in the application:
- Receive packets 0-4095
- Read all zeros although completion.packets and completion.payload_length show a packet has been received where packets 4096-8191 would be expected
- Receive packets 8192-12287
- Receive packets 4096-8191
- Receive packets 16384-20479
- Receive packets 12288-16387
....

The pattern is repeated for greater values of ring_cyclicb.num, with the chunks of received packets being always half of that value. Is there a way to guarantee in order packet delivery to the application?

**Comment by rafiw** [comment]
Hi @mplachecki,
thank you for using VMA.
The issue you describe sounds like a bug we are currently investigating.
if you can please send also your linux version and kernel to my email
rafiw@mellanox.com
so i can check if it's the same issue.
Thanks

**Comment by mplachecki** [comment]
We are using RedHat 7.3
3.10.0-514.16.1.el7.x86_64

**Comment by rafiw** [comment]
issue fixed in latest OFED

**Comment by liranoz12** [comment]
@mplachecki,
If issue still exists please open the thread.
Thanks,
Liran
